# This workflow will do a clean install of node dependencies, install firebase and deploy with a CI key

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install deps
      run: npm install
    - name: install firebase
      run: npm i -g firebase-tools
    - name: run build
      run: npm run export
    - name: deploy to firebase
      run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_CLI_KEY }}
      env:
        CI: true
